google_domain_name = "tapjangul.com"
google_project_name = "My First Project"
google_project_id = "perfect-nature-298302"
google_bucket_name = "tapjanguls-fuchi-bucket"
deployment_environment = "dev"
credentials = "fuchicorp-service-account.json"
deployment_name = "hello-world"
